language: objective-c

before_install:
  - gem install xcpretty
  - gem install cocoapods -v '1.2.1'
  - pod repo update

osx_image: xcode8.3

cache: cocoapods

env:
  global:
    - WORKSPACE=GEOSwift.xcworkspace
    - SCHEME=GEOSwift
    - SDK=iphonesimulator10.3
  matrix:
    # - DESTINATION="OS=10.3,name=iPhone 6"
    - DESTINATION="OS=9.3,name=iPhone 6"
    # - DESTINATION="OS=8.3,name=iPhone 6"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild
    -workspace "$WORKSPACE"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    clean test | xcpretty -c;

  - xcodebuild
    -workspace "$WORKSPACE"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Release
    ONLY_ACTIVE_ARCH=YES
    ENABLE_TESTABILITY=YES
    clean test | xcpretty -c;
